### PR TITLE
Make peer to peer Node mDNS optional, and unicast DNS preferred

### PR DESCRIPTION
**Pull request by andrewbonney**

### CODE REVIEW

**Comment by peterbrightwell** [comment]
@andrewbonney: can we merge this now?

**Comment by andrewbonney** [comment]
Not quite. Given the issues in some common DNS-SD libs we think it'd be worth getting https://github.com/AMWA-TV/nmos-discovery-registration/pull/71 in at the same time. I just need to add a couple of clarifications to that which I'll attempt to get done today.

**Comment by garethsb** [comment]
Should there also be a few changes to [3.0 Discovery](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.x/docs/3.0.%20Discovery.md) advice? E.g. clarifying operation in mDNS or unicast DNS-SD only modes, and the use of 'api_ver' as well as 'pri' to prioritise the results.

**Comment by andrewbonney** [comment]
@garethsb-sony were your queries here addressed by https://github.com/AMWA-TV/nmos-discovery-registration/pull/71 or do you think something further is required for this PR?

**Comment by garethsb** [comment]
I think everything addressed between #71 and your commits in this PR on 14 Dec. Thanks, Andrew!

**Pull request merged**
