### PR TITLE
Add proposed additions to support IS-06 LLDP requirements

### PR DESCRIPTION
**Pull request by andrewbonney**

### CODE REVIEW

**Comment by garethsb** [comment]
I'm sorry, I've lost track; please would you remind me why this isn't merged to v1.3-dev?

**Comment by andrewbonney** [comment]
It's mostly been waiting on any further input related to the future direction of IS-06. I suspect the additions will be useful anyway, and as they're optional there's no real harm in merging them if they look suitable. I'd be happy to resolve the conflict and merge in if you think the changes look appropriate.

**Comment by garethsb** [comment]
Hmm, interesting - I'll canvas opinion.

**Comment by peterbrightwell** [comment]
I'll remind the IS-06 team we're waiting for input.

**Comment by NEOAdvancedTechnology** [comment]
Looks good!

**Pull request merged**
