### PR TITLE
Possible alternative language on Query API Behaviour

### PR DESCRIPTION
**Pull request by peterbrightwell**
This is a possible rewording based on a comment in the mega-conversation. Not sure if it's right though so take a look

### CODE REVIEW

**Comment by garethsb** [comment]
I have a few minor quibbles with the rewording but there are bigger issues that could be resolved if we tackled the whole page. The previous/parent heading 'Creating a WebSocket subscription' already states some of what is under the 'Query API Behaviour' heading, and the whole is just misleading or at least confusing with respect to persistent vs non-persistent connections (a client is _required_ to specify the `persist` flag so there's no reason to talk primarily about one type and the other as an after-thought).

Are we OK to change the headings/fragment ids in a patch release? If so, I could try a slightly larger rewrite if you like?

**Comment by peterbrightwell** [comment]
@garethsb That would be good. I think changing headings would still be editorial (unless proved otherwise) so ok for a point release.

**Comment by garethsb** [comment]
One of the best references for the HTTP/1.1 Protocol Upgrade mechanism used for WebSocket is https://developer.mozilla.org/en-US/docs/Web/HTTP/Protocol_upgrade_mechanism, but perhaps that's more appropriate in a future INFO-xxx implementation guide than directly here in IS-04?

**Comment by peterbrightwell** [comment]
@garethsb Your text in 27b43cc looks good.  @andrewbonney can you take a look also?

**Comment by andrewbonney** [comment]
> @garethsb Your text in [27b43cc](https://github.com/AMWA-TV/nmos-discovery-registration/commit/27b43ccd9dfbd6d5b9da5473906ea9962423c0a2) looks good. @andrewbonney can you take a look also?

Looks good to me

**Pull request merged**
